set_attack_value(AT_NSPECIAL_KRAG, AG_CATEGORY, 2);
set_attack_value(AT_NSPECIAL_KRAG, AG_SPRITE, sprite_get("AT_NSPECIAL_KRAGG_SLAM"));
set_attack_value(AT_NSPECIAL_KRAG, AG_NUM_WINDOWS, 3);
set_attack_value(AT_NSPECIAL_KRAG, AG_HAS_LANDING_LAG, 4);
set_attack_value(AT_NSPECIAL_KRAG, AG_AIR_SPRITE, sprite_get("AT_NSPECIAL_KRAGG_SLAM"));
set_attack_value(AT_NSPECIAL_KRAG, AG_HURTBOX_SPRITE, sprite_get("AT_FSPECIAL_AIR_hurt"));

set_window_value(AT_NSPECIAL_KRAG, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_KRAG, 1, AG_WINDOW_LENGTH, 15);
set_window_value(AT_NSPECIAL_KRAG, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_NSPECIAL_KRAG, 1, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_NSPECIAL_KRAG, 1, AG_WINDOW_SFX, asset_get("sfx_zetter_downb"));
set_window_value(AT_NSPECIAL_KRAG, 1, AG_WINDOW_SFX_FRAME, 14);

set_window_value(AT_NSPECIAL_KRAG, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_KRAG, 2, AG_WINDOW_LENGTH, 10);
set_window_value(AT_NSPECIAL_KRAG, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_NSPECIAL_KRAG, 2, AG_WINDOW_ANIM_FRAME_START, 2);

set_window_value(AT_NSPECIAL_KRAG, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_KRAG, 3, AG_WINDOW_LENGTH, 15);
set_window_value(AT_NSPECIAL_KRAG, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_NSPECIAL_KRAG, 3, AG_WINDOW_ANIM_FRAME_START, 5);

set_num_hitboxes(AT_NSPECIAL_KRAG, 4);

set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_WINDOW, 4);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_LIFETIME, 30);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_HITBOX_X, 48);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_HITBOX_Y, -80);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_WIDTH, 80);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_HEIGHT, 30);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_ANGLE, 361);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_KNOCKBACK_SCALING, 0.4);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_VISUAL_EFFECT, 193);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_HIT_SFX, asset_get("sfx_blow_weak1"));
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_PROJECTILE_SPRITE, sprite_get("bug_spike1_spr"));
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_PROJECTILE_MASK, sprite_get("bug_spike1_mask"));
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_PROJECTILE_ANIM_SPEED, 0.2);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_NSPECIAL_KRAG, 1, HG_PROJECTILE_PARRY_STUN, 1);

set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_WINDOW, 4);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_LIFETIME, 30);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_HITBOX_X, 90);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_HITBOX_Y, -80);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_WIDTH, 80);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_HEIGHT, 30);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_DAMAGE, 4);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_ANGLE, 361);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_KNOCKBACK_SCALING, 0.4);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_VISUAL_EFFECT, 193);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_PROJECTILE_SPRITE, sprite_get("bug_spike2_spr"));
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_PROJECTILE_MASK, sprite_get("bug_spike2_mask"));
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_PROJECTILE_ANIM_SPEED, 0.2);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_NSPECIAL_KRAG, 2, HG_PROJECTILE_PARRY_STUN, 1);

set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_WINDOW, 4);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_LIFETIME, 30);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_HITBOX_X, 160);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_HITBOX_Y, -80);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_WIDTH, 80);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_HEIGHT, 30);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_DAMAGE, 10);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_ANGLE, 90);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_BASE_KNOCKBACK, 11);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_KNOCKBACK_SCALING, 0.2);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_VISUAL_EFFECT, 192);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_HITSTUN_MULTIPLIER, 1.2);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_PROJECTILE_SPRITE, sprite_get("bug_spike3_spr"));
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_PROJECTILE_MASK, sprite_get("bug_spike3_mask"));
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_PROJECTILE_ANIM_SPEED, 0.2);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_NSPECIAL_KRAG, 3, HG_PROJECTILE_PARRY_STUN, 1);

set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_WINDOW, 4);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_LIFETIME, 3);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_HITBOX_X, 28);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_HITBOX_Y, -30);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_WIDTH, 60);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_HEIGHT, 60);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_SHAPE, 0);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_PRIORITY, 2);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_DAMAGE, 14);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_ANGLE, 300);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_KNOCKBACK_SCALING, 0.9);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_VISUAL_EFFECT, 193);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_NSPECIAL_KRAG, 4, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));