set_attack_value(AT_NSPECIAL_ELLI, AG_CATEGORY, 2);
set_attack_value(AT_NSPECIAL_ELLI, AG_SPRITE, sprite_get("AT_NSPECIAL_ELLI"));
set_attack_value(AT_NSPECIAL_ELLI, AG_NUM_WINDOWS, 3);
set_attack_value(AT_NSPECIAL_ELLI, AG_AIR_SPRITE, sprite_get("AT_NSPECIAL_ELLI"));
set_attack_value(AT_NSPECIAL_ELLI, AG_HURTBOX_SPRITE, sprite_get("AT_NSPECIAL_ELLI_hurt"));

set_window_value(AT_NSPECIAL_ELLI, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_ELLI, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_NSPECIAL_ELLI, 1, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_NSPECIAL_ELLI, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NSPECIAL_ELLI, 1, AG_WINDOW_SFX, asset_get("sfx_ell_dtilt2"));
set_window_value(AT_NSPECIAL_ELLI, 1, AG_WINDOW_SFX_FRAME, 8);
set_window_value(AT_NSPECIAL_ELLI, 1, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_NSPECIAL_ELLI, 1, AG_WINDOW_HSPEED_TYPE, 1);

set_window_value(AT_NSPECIAL_ELLI, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_ELLI, 2, AG_WINDOW_LENGTH, 30);
set_window_value(AT_NSPECIAL_ELLI, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NSPECIAL_ELLI, 2, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_NSPECIAL_ELLI, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_NSPECIAL_ELLI, 2, AG_WINDOW_HSPEED_TYPE, 1);

set_window_value(AT_NSPECIAL_ELLI, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_ELLI, 3, AG_WINDOW_LENGTH, 30);
set_window_value(AT_NSPECIAL_ELLI, 3, AG_WINDOW_ANIM_FRAMES, 9);
set_window_value(AT_NSPECIAL_ELLI, 3, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(AT_NSPECIAL_ELLI, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NSPECIAL_ELLI, 3, AG_WINDOW_SFX, asset_get("sfx_ell_fist_fire"));
set_window_value(AT_NSPECIAL_ELLI, 3, AG_WINDOW_SFX_FRAME, 0);

set_num_hitboxes(AT_NSPECIAL_ELLI, 2);

set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_WINDOW, 3);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_LIFETIME, 16);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_HITBOX_X, 32);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_HITBOX_Y, -16);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_WIDTH, 80);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_HEIGHT, 30);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_DAMAGE, 4);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_ANGLE, 45);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_KNOCKBACK_SCALING, 0.3);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_HITSTUN_MULTIPLIER, 0.8);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_PROJECTILE_SPRITE, sprite_get("AT_NSPECIAL_ELLI_FIST"));
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_PROJECTILE_MASK, sprite_get("AT_NSPECIAL_ELLI_FIST"));
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_PROJECTILE_ANIM_SPEED, 0.8);
set_hitbox_value(AT_NSPECIAL_ELLI, 1, HG_PROJECTILE_HSPEED, 15);

set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_WINDOW, 4);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_LIFETIME, 10);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_HITBOX_X, 32);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_HITBOX_Y, -32);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_WIDTH, 80);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_HEIGHT, 30);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_PRIORITY, 7);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_DAMAGE, 9);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_ANGLE, 45);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_VISUAL_EFFECT, 143);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_HITSTUN_MULTIPLIER, 0.8);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_HIT_SFX, asset_get("sfx_ell_strong_attack_explosion"));
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_BASE_HITPAUSE, 12);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_PROJECTILE_MASK, sprite_get("AT_NSPECIAL_ELLI_FIST"));
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_PROJECTILE_ANIM_SPEED, 0.8);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_NSPECIAL_ELLI, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);